version: '0.1'

services:
  app:
    build: .
    command: python -u app.py
    environment:
      - FLASK_ENV=prod
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    environment:
      - MONGO_HOST=mongo
    ports:
      - 27017:27017
    volumes:
      - /corider:/data/db